---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: bmc-shim
  annotations:
    io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: "true"
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "1"
    pipelinesascode.tekton.dev/target-namespace: "homelab"
    pipelinesascode.tekton.dev/task: "https://raw.githubusercontent.com/ArthurVardevanyan/HomeLab/main/tekton/tasks/git-clone/0.9.1/git-clone.yaml"
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/ArthurVardevanyan/HomeLab/main/tekton/base/clair-action/clair-action-task.yaml"
spec:
  params:
    - name: git-url
      value: "{{ repo_url }}"
    - name: git-commit
      value: "{{ revision }}"
    - name: pull-request-number
      value: "{{ pull_request_number }}"
    - name: event
      value: "{{ event_type }}"
  pipelineSpec:
    params:
      - name: git-url
        description: Repository URL to clone from.
        type: string
      - name: git-commit
        type: string
      - name: pull-request-number
        type: string
      - name: event
        type: string

    results:
      - description: The common vulnerabilities and exposures (CVE) result
        name: SCAN_OUTPUT
        value: $(tasks.clair-action.results.SCAN_OUTPUT)

    workspaces:
      - name: data
      - name: git_auth_secret

    tasks:
      - name: git-clone
        when:
          - input: "$(params.event)"
            operator: in
            values: ["pull_request"]
        taskRef:
          name: git-clone
          kind: Task
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.git-commit)
        workspaces:
          - name: output
            workspace: data
          - name: basic-auth
            workspace: git_auth_secret

      - name: test-build
        runAfter:
          - git-clone
        when:
          - input: "$(params.event)"
            operator: in
            values: ["pull_request"]
        workspaces:
          - name: output
            workspace: data
          - name: basic-auth
            workspace: git_auth_secret
        params:
          - name: revision
            value: $(params.git-commit)
          - name: pull-request-number
            value: $(params.pull-request-number)
        taskSpec:
          params:
            - name: revision
              type: string
            - name: pull-request-number
              type: string
              default: ""
          results:
            - name: IMAGE
          workspaces:
            - name: output
              optional: false
            - name: basic-auth
              optional: false
          stepTemplate:
            name: stepTemplate
            resources:
              requests:
                memory: 500Mi
                cpu: 500m
                ephemeral-storage: 100Mi
              limits:
                cpu: "4"
                memory: 5Gi
                ephemeral-storage: 100Mi
            securityContext:
              privileged: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: cache
          steps:
            - name: test-build
              image: registry.arthurvardevanyan.com/homelab/toolbox:not_latest
              env:
                - name: WORKSPACE_DATA_PATH
                  value: $(workspaces.output.path)
                - name: WORKSPACE_RESULTS_PATH
                  value: $(results.IMAGE.path)
              volumeMounts:
                - name: cache
                  mountPath: /go/pkg
                  subpath: go
                - name: cache
                  mountPath: /tmp
                  subpath: tmp
              script: |
                set -o errexit
                set -o nounset
                set -o pipefail

                cd ${WORKSPACE_DATA_PATH}

                GIT_PR=$(params.pull-request-number)
                GIT_SHA=$(params.revision)
                export TAG="pr-${GIT_PR}-${GIT_SHA}"
                make ko-build-pipeline

      - name: promote
        runAfter:
          - git-clone
        when:
          - input: "$(params.event)"
            operator: in
            values: ["push"]
        workspaces:
          - name: basic-auth
            workspace: git_auth_secret
        params:
          - name: revision
            value: $(params.git-commit)
          - name: git-url
            value: $(params.git-url)
        taskSpec:
          params:
            - name: revision
              type: string
            - name: git-url
              type: string
          workspaces:
            - name: basic-auth
              optional: false
          results:
            - name: IMAGE
          stepTemplate:
            name: stepTemplate
            resources:
              requests:
                memory: 64Mi
                cpu: 50m
                ephemeral-storage: 100Mi
              limits:
                cpu: "100m"
                memory: 128Mi
                ephemeral-storage: 100Mi
            securityContext:
              privileged: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL
          steps:
            - name: promote
              image: registry.arthurvardevanyan.com/homelab/toolbox:not_latest
              env:
                - name: WORKSPACE_RESULTS_PATH
                  value: $(results.IMAGE.path)
              script: |
                set -o errexit
                set -o nounset
                set -o pipefail

                cd ${WORKSPACE_DATA_PATH}
                git config --global --add safe.directory "${WORKSPACE_DATA_PATH}"

                gh auth login --hostname "github.com" --with-token <"$(workspaces.basic-auth.path)/git-provider-token"

                echo "Get PR Number"
                GIT_PR=$(gh pr list --repo $(params.git-url) --search "$(params.revision)" --state merged --json url | jq --raw-output '.[] | .url' | rev | cut -d/ -f1 | rev)
                echo "Get PR SHA"
                GIT_SHA=$(gh pr view $GIT_PR --repo $(params.git-url) --json headRefOid --jq .headRefOid)

                export REPO=$(grep "export KO_DOCKER_REPO" Makefile | cut -d= -f2)
                export PR_TAG="pr-${GIT_PR}-${GIT_SHA}"
                export NEW_TAG=$(date -u +"%Y.%m.%d.%H%M%S")-pr${GIT_PR}

                echo "Promoting ${REPO}:${PR_TAG} to ${REPO}:${NEW_TAG}"
                skopeo copy --all --preserve-digests docker://${REPO}:${PR_TAG} docker://${REPO}:${NEW_TAG}
                echo "${REPO}:${NEW_TAG}" > ${WORKSPACE_RESULTS_PATH}

      - name: clair-action-pr
        runAfter:
          - test-build
        when:
          - input: "$(params.event)"
            operator: in
            values: ["pull_request"]
        taskRef:
          name: clair-action
          kind: Task
        params:
          - name: IMAGE
            value: $(tasks.test-build.results.IMAGE)

      - name: clair-action-push
        runAfter:
          - promote
        when:
          - input: "$(params.event)"
            operator: in
            values: ["push"]
        taskRef:
          name: clair-action
          kind: Task
        params:
          - name: IMAGE
            value: $(tasks.promote.results.IMAGE)

  taskRunTemplate:
    serviceAccountName: pipeline
    podTemplate:
      runtimeClassName: selinux
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
  workspaces:
    - name: data
      volumeClaimTemplate:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "200Mi"
          storageClassName: rook-ceph-block-ci
    - name: git_auth_secret
      secret:
        secretName: "{{ git_auth_secret }}"
